//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.ACMA.BusinessLogic.DNCRServicesRegistration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineRegisterRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class OnlineRegisterRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FaxNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhoneNumbersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FaxNumbers {
            get {
                return this.FaxNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumbersField, value) != true)) {
                    this.FaxNumbersField = value;
                    this.RaisePropertyChanged("FaxNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganisationName {
            get {
                return this.OrganisationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationNameField, value) != true)) {
                    this.OrganisationNameField = value;
                    this.RaisePropertyChanged("OrganisationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhoneNumbers {
            get {
                return this.PhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumbersField, value) != true)) {
                    this.PhoneNumbersField = value;
                    this.RaisePropertyChanged("PhoneNumbers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineRegistrationRequestResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class OnlineRegistrationRequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasEmailSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegistrationRequestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEmailSent {
            get {
                return this.HasEmailSentField;
            }
            set {
                if ((this.HasEmailSentField.Equals(value) != true)) {
                    this.HasEmailSentField = value;
                    this.RaisePropertyChanged("HasEmailSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegistrationRequestID {
            get {
                return this.RegistrationRequestIDField;
            }
            set {
                if ((this.RegistrationRequestIDField.Equals(value) != true)) {
                    this.RegistrationRequestIDField = value;
                    this.RaisePropertyChanged("RegistrationRequestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
    [System.SerializableAttribute()]
    public partial class DncrServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFaultReason[] ReasonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationToken {
            get {
                return this.CorrelationTokenField;
            }
            set {
                if ((this.CorrelationTokenField.Equals(value) != true)) {
                    this.CorrelationTokenField = value;
                    this.RaisePropertyChanged("CorrelationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionTypeFullName {
            get {
                return this.ExceptionTypeFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeFullNameField, value) != true)) {
                    this.ExceptionTypeFullNameField = value;
                    this.RaisePropertyChanged("ExceptionTypeFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFaultReason[] Reasons {
            get {
                return this.ReasonsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonsField, value) != true)) {
                    this.ReasonsField = value;
                    this.RaisePropertyChanged("Reasons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DncrServiceFaultReason", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
    [System.SerializableAttribute()]
    public partial class DncrServiceFaultReason : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName {
            get {
                return this.PropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNameField, value) != true)) {
                    this.PropertyNameField = value;
                    this.RaisePropertyChanged("PropertyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmOnlineRegistrationRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class ConfirmOnlineRegistrationRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationToken {
            get {
                return this.ActivationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationTokenField, value) != true)) {
                    this.ActivationTokenField = value;
                    this.RaisePropertyChanged("ActivationToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmOnlineRegistrationResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class ConfirmOnlineRegistrationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTokenConsumedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTokenExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegisteredNumberCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTokenConsumed {
            get {
                return this.IsTokenConsumedField;
            }
            set {
                if ((this.IsTokenConsumedField.Equals(value) != true)) {
                    this.IsTokenConsumedField = value;
                    this.RaisePropertyChanged("IsTokenConsumed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTokenExpired {
            get {
                return this.IsTokenExpiredField;
            }
            set {
                if ((this.IsTokenExpiredField.Equals(value) != true)) {
                    this.IsTokenExpiredField = value;
                    this.RaisePropertyChanged("IsTokenExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegisteredNumberCount {
            get {
                return this.RegisteredNumberCountField;
            }
            set {
                if ((this.RegisteredNumberCountField.Equals(value) != true)) {
                    this.RegisteredNumberCountField = value;
                    this.RaisePropertyChanged("RegisteredNumberCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckOnlineRegisterRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class CheckOnlineRegisterRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NumbersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Numbers {
            get {
                return this.NumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersField, value) != true)) {
                    this.NumbersField = value;
                    this.RaisePropertyChanged("Numbers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineCheckRegistrationRequestResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class OnlineCheckRegistrationRequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasEmailSentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasEmailSent {
            get {
                return this.HasEmailSentField;
            }
            set {
                if ((this.HasEmailSentField.Equals(value) != true)) {
                    this.HasEmailSentField = value;
                    this.RaisePropertyChanged("HasEmailSent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkRegistrationRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n.Bulk")]
    [System.SerializableAttribute()]
    public partial class BulkRegistrationRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EvidenceFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FaxNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] NumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestTypeBulkRegistrationRequestTypeEnum OperationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRServicesRegistration.RegistrationRequestAccountContactPreferenceRegistrationRequestAccountContactPreferenceEnum PreferredContactMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] EvidenceFile {
            get {
                return this.EvidenceFileField;
            }
            set {
                if ((object.ReferenceEquals(this.EvidenceFileField, value) != true)) {
                    this.EvidenceFileField = value;
                    this.RaisePropertyChanged("EvidenceFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FaxNumbersFile {
            get {
                return this.FaxNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumbersFileField, value) != true)) {
                    this.FaxNumbersFileField = value;
                    this.RaisePropertyChanged("FaxNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] NumbersFile {
            get {
                return this.NumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersFileField, value) != true)) {
                    this.NumbersFileField = value;
                    this.RaisePropertyChanged("NumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestTypeBulkRegistrationRequestTypeEnum OperationType {
            get {
                return this.OperationTypeField;
            }
            set {
                if ((this.OperationTypeField.Equals(value) != true)) {
                    this.OperationTypeField = value;
                    this.RaisePropertyChanged("OperationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.RegistrationRequestAccountContactPreferenceRegistrationRequestAccountContactPreferenceEnum PreferredContactMethod {
            get {
                return this.PreferredContactMethodField;
            }
            set {
                if ((this.PreferredContactMethodField.Equals(value) != true)) {
                    this.PreferredContactMethodField = value;
                    this.RaisePropertyChanged("PreferredContactMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkRegistrationRequestType.BulkRegistrationRequestTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Reference")]
    public enum BulkRegistrationRequestTypeBulkRegistrationRequestTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deregister = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Check = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationRequestAccountContactPreference.RegistrationRequestAccountContactPref" +
        "erenceEnum", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Reference")]
    public enum RegistrationRequestAccountContactPreferenceRegistrationRequestAccountContactPreferenceEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Post = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkRegistrationRequestResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Registratio" +
        "n.Bulk")]
    [System.SerializableAttribute()]
    public partial class BulkRegistrationRequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ErrorsInFaxFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ErrorsInPhoneFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsInFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsInPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ErrorsInFaxFile {
            get {
                return this.ErrorsInFaxFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsInFaxFileField, value) != true)) {
                    this.ErrorsInFaxFileField = value;
                    this.RaisePropertyChanged("ErrorsInFaxFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ErrorsInPhoneFile {
            get {
                return this.ErrorsInPhoneFileField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsInPhoneFileField, value) != true)) {
                    this.ErrorsInPhoneFileField = value;
                    this.RaisePropertyChanged("ErrorsInPhoneFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrorsInFax {
            get {
                return this.HasErrorsInFaxField;
            }
            set {
                if ((this.HasErrorsInFaxField.Equals(value) != true)) {
                    this.HasErrorsInFaxField = value;
                    this.RaisePropertyChanged("HasErrorsInFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrorsInPhone {
            get {
                return this.HasErrorsInPhoneField;
            }
            set {
                if ((this.HasErrorsInPhoneField.Equals(value) != true)) {
                    this.HasErrorsInPhoneField = value;
                    this.RaisePropertyChanged("HasErrorsInPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dncrapp/", ConfigurationName="DNCRServicesRegistration.IOnlineRegistrationService")]
    public interface IOnlineRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Register", ReplyAction="http://dncrapp/IOnlineRegistrationService/RegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFault), Action="http://dncrapp/IOnlineRegistrationService/RegisterDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegistrationRequestResult Register(SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegisterRequestArgs onlineRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Register", ReplyAction="http://dncrapp/IOnlineRegistrationService/RegisterResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegistrationRequestResult> RegisterAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegisterRequestArgs onlineRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Confirm", ReplyAction="http://dncrapp/IOnlineRegistrationService/ConfirmResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFault), Action="http://dncrapp/IOnlineRegistrationService/ConfirmDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationResult Confirm(SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationRequestArgs confirmRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Confirm", ReplyAction="http://dncrapp/IOnlineRegistrationService/ConfirmResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationResult> ConfirmAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationRequestArgs confirmRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Check", ReplyAction="http://dncrapp/IOnlineRegistrationService/CheckResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFault), Action="http://dncrapp/IOnlineRegistrationService/CheckDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineCheckRegistrationRequestResult Check(SD.ACMA.BusinessLogic.DNCRServicesRegistration.CheckOnlineRegisterRequestArgs checkOnlineRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/Check", ReplyAction="http://dncrapp/IOnlineRegistrationService/CheckResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineCheckRegistrationRequestResult> CheckAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.CheckOnlineRegisterRequestArgs checkOnlineRegistrationRequestArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/SubmitBulkRegistrationRequest", ReplyAction="http://dncrapp/IOnlineRegistrationService/SubmitBulkRegistrationRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRServicesRegistration.DncrServiceFault), Action="http://dncrapp/IOnlineRegistrationService/SubmitBulkRegistrationRequestDncrServic" +
            "eFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestResult SubmitBulkRegistrationRequest(SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestArgs bulkRegistrationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineRegistrationService/SubmitBulkRegistrationRequest", ReplyAction="http://dncrapp/IOnlineRegistrationService/SubmitBulkRegistrationRequestResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestResult> SubmitBulkRegistrationRequestAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestArgs bulkRegistrationRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineRegistrationServiceChannel : SD.ACMA.BusinessLogic.DNCRServicesRegistration.IOnlineRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineRegistrationServiceClient : System.ServiceModel.ClientBase<SD.ACMA.BusinessLogic.DNCRServicesRegistration.IOnlineRegistrationService>, SD.ACMA.BusinessLogic.DNCRServicesRegistration.IOnlineRegistrationService {
        
        public OnlineRegistrationServiceClient() {
        }
        
        public OnlineRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegistrationRequestResult Register(SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegisterRequestArgs onlineRegistrationRequestArgs) {
            return base.Channel.Register(onlineRegistrationRequestArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegistrationRequestResult> RegisterAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineRegisterRequestArgs onlineRegistrationRequestArgs) {
            return base.Channel.RegisterAsync(onlineRegistrationRequestArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationResult Confirm(SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationRequestArgs confirmRegistrationRequestArgs) {
            return base.Channel.Confirm(confirmRegistrationRequestArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationResult> ConfirmAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.ConfirmOnlineRegistrationRequestArgs confirmRegistrationRequestArgs) {
            return base.Channel.ConfirmAsync(confirmRegistrationRequestArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineCheckRegistrationRequestResult Check(SD.ACMA.BusinessLogic.DNCRServicesRegistration.CheckOnlineRegisterRequestArgs checkOnlineRegistrationRequestArgs) {
            return base.Channel.Check(checkOnlineRegistrationRequestArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.OnlineCheckRegistrationRequestResult> CheckAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.CheckOnlineRegisterRequestArgs checkOnlineRegistrationRequestArgs) {
            return base.Channel.CheckAsync(checkOnlineRegistrationRequestArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestResult SubmitBulkRegistrationRequest(SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestArgs bulkRegistrationRequest) {
            return base.Channel.SubmitBulkRegistrationRequest(bulkRegistrationRequest);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestResult> SubmitBulkRegistrationRequestAsync(SD.ACMA.BusinessLogic.DNCRServicesRegistration.BulkRegistrationRequestArgs bulkRegistrationRequest) {
            return base.Channel.SubmitBulkRegistrationRequestAsync(bulkRegistrationRequest);
        }
    }
}
