IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FinancialReport' AND COLUMN_NAME = 'MarkedFinalBy')
BEGIN
	ALTER TABLE FinancialReport
		ADD MarkedFinalBy nvarchar(50) NULL
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FinancialReport' AND COLUMN_NAME = 'Status')
BEGIN
	ALTER TABLE FinancialReport
		ADD Status nvarchar(50) NULL
END
GO