//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.ACMA.BusinessLogic.DNCRWashingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuickWashRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class QuickWashRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserContextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientReference {
            get {
                return this.ClientReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientReferenceField, value) != true)) {
                    this.ClientReferenceField = value;
                    this.RaisePropertyChanged("ClientReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Numbers {
            get {
                return this.NumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersField, value) != true)) {
                    this.NumbersField = value;
                    this.RaisePropertyChanged("Numbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserContext {
            get {
                return this.UserContextField;
            }
            set {
                if ((object.ReferenceEquals(this.UserContextField, value) != true)) {
                    this.UserContextField = value;
                    this.RaisePropertyChanged("UserContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineUserContext", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class OnlineUserContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountUserID {
            get {
                return this.AccountUserIDField;
            }
            set {
                if ((this.AccountUserIDField.Equals(value) != true)) {
                    this.AccountUserIDField = value;
                    this.RaisePropertyChanged("AccountUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((this.AgentIDField.Equals(value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuickWashResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class QuickWashResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasInValidNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSufficientWashingCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasValidSubscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.WashNumber[] NumbersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasInValidNumbers {
            get {
                return this.HasInValidNumbersField;
            }
            set {
                if ((this.HasInValidNumbersField.Equals(value) != true)) {
                    this.HasInValidNumbersField = value;
                    this.RaisePropertyChanged("HasInValidNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSufficientWashingCredits {
            get {
                return this.HasSufficientWashingCreditsField;
            }
            set {
                if ((this.HasSufficientWashingCreditsField.Equals(value) != true)) {
                    this.HasSufficientWashingCreditsField = value;
                    this.RaisePropertyChanged("HasSufficientWashingCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasValidSubscription {
            get {
                return this.HasValidSubscriptionField;
            }
            set {
                if ((this.HasValidSubscriptionField.Equals(value) != true)) {
                    this.HasValidSubscriptionField = value;
                    this.RaisePropertyChanged("HasValidSubscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashNumber[] Numbers {
            get {
                return this.NumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.NumbersField, value) != true)) {
                    this.NumbersField = value;
                    this.RaisePropertyChanged("Numbers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashNumber", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagField, value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
    [System.SerializableAttribute()]
    public partial class DncrServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFaultReason[] ReasonsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationToken {
            get {
                return this.CorrelationTokenField;
            }
            set {
                if ((this.CorrelationTokenField.Equals(value) != true)) {
                    this.CorrelationTokenField = value;
                    this.RaisePropertyChanged("CorrelationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionTypeFullName {
            get {
                return this.ExceptionTypeFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeFullNameField, value) != true)) {
                    this.ExceptionTypeFullNameField = value;
                    this.RaisePropertyChanged("ExceptionTypeFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFaultReason[] Reasons {
            get {
                return this.ReasonsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonsField, value) != true)) {
                    this.ReasonsField = value;
                    this.RaisePropertyChanged("Reasons");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DncrServiceFaultReason", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
    [System.SerializableAttribute()]
    public partial class DncrServiceFaultReason : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName {
            get {
                return this.PropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNameField, value) != true)) {
                    this.PropertyNameField = value;
                    this.RaisePropertyChanged("PropertyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashFileRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashFileRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WashResultFormatFileWithIndicatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WashResultFormatInvalidNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WashResultFormatRegisteredNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WashResultFormatUnregisteredNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WashResultFormatFileWithIndicators {
            get {
                return this.WashResultFormatFileWithIndicatorsField;
            }
            set {
                if ((this.WashResultFormatFileWithIndicatorsField.Equals(value) != true)) {
                    this.WashResultFormatFileWithIndicatorsField = value;
                    this.RaisePropertyChanged("WashResultFormatFileWithIndicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WashResultFormatInvalidNumbers {
            get {
                return this.WashResultFormatInvalidNumbersField;
            }
            set {
                if ((this.WashResultFormatInvalidNumbersField.Equals(value) != true)) {
                    this.WashResultFormatInvalidNumbersField = value;
                    this.RaisePropertyChanged("WashResultFormatInvalidNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WashResultFormatRegisteredNumbers {
            get {
                return this.WashResultFormatRegisteredNumbersField;
            }
            set {
                if ((this.WashResultFormatRegisteredNumbersField.Equals(value) != true)) {
                    this.WashResultFormatRegisteredNumbersField = value;
                    this.RaisePropertyChanged("WashResultFormatRegisteredNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WashResultFormatUnregisteredNumbers {
            get {
                return this.WashResultFormatUnregisteredNumbersField;
            }
            set {
                if ((this.WashResultFormatUnregisteredNumbersField.Equals(value) != true)) {
                    this.WashResultFormatUnregisteredNumbersField = value;
                    this.RaisePropertyChanged("WashResultFormatUnregisteredNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashFileResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllInOneFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSufficientWashingCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasValidSubscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvalidNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.WashingStatusWashingStatusEnum StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnregisteredNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllInOneFile {
            get {
                return this.AllInOneFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AllInOneFileField, value) != true)) {
                    this.AllInOneFileField = value;
                    this.RaisePropertyChanged("AllInOneFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSufficientWashingCredits {
            get {
                return this.HasSufficientWashingCreditsField;
            }
            set {
                if ((this.HasSufficientWashingCreditsField.Equals(value) != true)) {
                    this.HasSufficientWashingCreditsField = value;
                    this.RaisePropertyChanged("HasSufficientWashingCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasValidSubscription {
            get {
                return this.HasValidSubscriptionField;
            }
            set {
                if ((this.HasValidSubscriptionField.Equals(value) != true)) {
                    this.HasValidSubscriptionField = value;
                    this.RaisePropertyChanged("HasValidSubscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvalidNumbersFile {
            get {
                return this.InvalidNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.InvalidNumbersFileField, value) != true)) {
                    this.InvalidNumbersFileField = value;
                    this.RaisePropertyChanged("InvalidNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFile {
            get {
                return this.OriginalFileField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalFileField, value) != true)) {
                    this.OriginalFileField = value;
                    this.RaisePropertyChanged("OriginalFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisteredNumbersFile {
            get {
                return this.RegisteredNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredNumbersFileField, value) != true)) {
                    this.RegisteredNumbersFileField = value;
                    this.RaisePropertyChanged("RegisteredNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashingStatusWashingStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnregisteredNumbersFile {
            get {
                return this.UnregisteredNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.UnregisteredNumbersFileField, value) != true)) {
                    this.UnregisteredNumbersFileField = value;
                    this.RaisePropertyChanged("UnregisteredNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashCredits {
            get {
                return this.WashCreditsField;
            }
            set {
                if ((this.WashCreditsField.Equals(value) != true)) {
                    this.WashCreditsField = value;
                    this.RaisePropertyChanged("WashCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashingStatus.WashingStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Reference")]
    public enum WashingStatusWashingStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStarted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreWashFileOnlineArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class PreWashFileOnlineArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelativeInputFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserContextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientReference {
            get {
                return this.ClientReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientReferenceField, value) != true)) {
                    this.ClientReferenceField = value;
                    this.RaisePropertyChanged("ClientReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInputFilePath {
            get {
                return this.RelativeInputFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativeInputFilePathField, value) != true)) {
                    this.RelativeInputFilePathField = value;
                    this.RaisePropertyChanged("RelativeInputFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserContext {
            get {
                return this.UserContextField;
            }
            set {
                if ((object.ReferenceEquals(this.UserContextField, value) != true)) {
                    this.UserContextField = value;
                    this.RaisePropertyChanged("UserContext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreWashByFileResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class PreWashByFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountWashingCreditsBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FileNameAlreadyExistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasInValidNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasSufficientWashingCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasValidSubscriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFileFormatNotValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFileNameNotValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFileSizeExceedLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelativeInputFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequiredWashingCreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowWashQuoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountWashingCreditsBalance {
            get {
                return this.AccountWashingCreditsBalanceField;
            }
            set {
                if ((this.AccountWashingCreditsBalanceField.Equals(value) != true)) {
                    this.AccountWashingCreditsBalanceField = value;
                    this.RaisePropertyChanged("AccountWashingCreditsBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FileNameAlreadyExists {
            get {
                return this.FileNameAlreadyExistsField;
            }
            set {
                if ((this.FileNameAlreadyExistsField.Equals(value) != true)) {
                    this.FileNameAlreadyExistsField = value;
                    this.RaisePropertyChanged("FileNameAlreadyExists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasInValidNumbers {
            get {
                return this.HasInValidNumbersField;
            }
            set {
                if ((this.HasInValidNumbersField.Equals(value) != true)) {
                    this.HasInValidNumbersField = value;
                    this.RaisePropertyChanged("HasInValidNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSufficientWashingCredits {
            get {
                return this.HasSufficientWashingCreditsField;
            }
            set {
                if ((this.HasSufficientWashingCreditsField.Equals(value) != true)) {
                    this.HasSufficientWashingCreditsField = value;
                    this.RaisePropertyChanged("HasSufficientWashingCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasValidSubscription {
            get {
                return this.HasValidSubscriptionField;
            }
            set {
                if ((this.HasValidSubscriptionField.Equals(value) != true)) {
                    this.HasValidSubscriptionField = value;
                    this.RaisePropertyChanged("HasValidSubscription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFileFormatNotValid {
            get {
                return this.IsFileFormatNotValidField;
            }
            set {
                if ((this.IsFileFormatNotValidField.Equals(value) != true)) {
                    this.IsFileFormatNotValidField = value;
                    this.RaisePropertyChanged("IsFileFormatNotValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFileNameNotValid {
            get {
                return this.IsFileNameNotValidField;
            }
            set {
                if ((this.IsFileNameNotValidField.Equals(value) != true)) {
                    this.IsFileNameNotValidField = value;
                    this.RaisePropertyChanged("IsFileNameNotValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFileSizeExceedLimit {
            get {
                return this.IsFileSizeExceedLimitField;
            }
            set {
                if ((this.IsFileSizeExceedLimitField.Equals(value) != true)) {
                    this.IsFileSizeExceedLimitField = value;
                    this.RaisePropertyChanged("IsFileSizeExceedLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativeInputFilePath {
            get {
                return this.RelativeInputFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativeInputFilePathField, value) != true)) {
                    this.RelativeInputFilePathField = value;
                    this.RaisePropertyChanged("RelativeInputFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequiredWashingCredits {
            get {
                return this.RequiredWashingCreditsField;
            }
            set {
                if ((this.RequiredWashingCreditsField.Equals(value) != true)) {
                    this.RequiredWashingCreditsField = value;
                    this.RaisePropertyChanged("RequiredWashingCredits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowWashQuote {
            get {
                return this.ShowWashQuoteField;
            }
            set {
                if ((this.ShowWashQuoteField.Equals(value) != true)) {
                    this.ShowWashQuoteField = value;
                    this.RaisePropertyChanged("ShowWashQuote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadErrorLogRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class DownloadErrorLogRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadErrorLogResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class DownloadErrorLogResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadWashFileRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class DownloadWashFileRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.WashFileType WashFileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashFileType WashFileType {
            get {
                return this.WashFileTypeField;
            }
            set {
                if ((this.WashFileTypeField.Equals(value) != true)) {
                    this.WashFileTypeField = value;
                    this.RaisePropertyChanged("WashFileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashFileType", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    public enum WashFileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Original = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllInOne = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registered = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnRegistered = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadWashFileResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class DownloadWashFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExpiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExpired {
            get {
                return this.IsExpiredField;
            }
            set {
                if ((this.IsExpiredField.Equals(value) != true)) {
                    this.IsExpiredField = value;
                    this.RaisePropertyChanged("IsExpired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashingSearchRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashingSearchRequestArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<SD.ACMA.BusinessLogic.DNCRWashingService.WashingChannelWashingChannelEnum> ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExcludeWashWithOneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WashReferenceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<SD.ACMA.BusinessLogic.DNCRWashingService.WashingChannelWashingChannelEnum> Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((this.ChannelField.Equals(value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExcludeWashWithOneNumber {
            get {
                return this.ExcludeWashWithOneNumberField;
            }
            set {
                if ((this.ExcludeWashWithOneNumberField.Equals(value) != true)) {
                    this.ExcludeWashWithOneNumberField = value;
                    this.RaisePropertyChanged("ExcludeWashWithOneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.OnlineUserContext User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WashReferenceId {
            get {
                return this.WashReferenceIdField;
            }
            set {
                if ((this.WashReferenceIdField.Equals(value) != true)) {
                    this.WashReferenceIdField = value;
                    this.RaisePropertyChanged("WashReferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashingChannel.WashingChannelEnum", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Reference")]
    public enum WashingChannelWashingChannelEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineQuickCheck = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlineFileUpload = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutomatedWashingService = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RealTimeAccess = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashHistoryRequestResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashHistoryRequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchResult[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashHistoryMaxResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashHistoryMaxResults {
            get {
                return this.WashHistoryMaxResultsField;
            }
            set {
                if ((this.WashHistoryMaxResultsField.Equals(value) != true)) {
                    this.WashHistoryMaxResultsField = value;
                    this.RaisePropertyChanged("WashHistoryMaxResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WashingSearchResult", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Washing")]
    [System.SerializableAttribute()]
    public partial class WashingSearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgentUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AllInOneFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllInOneNumbersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanDownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasRefundedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvalidNumbersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvalidNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumbersWashedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegisteredNumbersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnregisteredNumbersCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnregisteredNumbersFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SD.ACMA.BusinessLogic.DNCRWashingService.WashingChannelWashingChannelEnum WashingChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WashingRequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountUserId {
            get {
                return this.AccountUserIdField;
            }
            set {
                if ((this.AccountUserIdField.Equals(value) != true)) {
                    this.AccountUserIdField = value;
                    this.RaisePropertyChanged("AccountUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountUserName {
            get {
                return this.AccountUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountUserNameField, value) != true)) {
                    this.AccountUserNameField = value;
                    this.RaisePropertyChanged("AccountUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AgentUserId {
            get {
                return this.AgentUserIdField;
            }
            set {
                if ((this.AgentUserIdField.Equals(value) != true)) {
                    this.AgentUserIdField = value;
                    this.RaisePropertyChanged("AgentUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentUserName {
            get {
                return this.AgentUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentUserNameField, value) != true)) {
                    this.AgentUserNameField = value;
                    this.RaisePropertyChanged("AgentUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllInOneFile {
            get {
                return this.AllInOneFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AllInOneFileField, value) != true)) {
                    this.AllInOneFileField = value;
                    this.RaisePropertyChanged("AllInOneFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllInOneNumbersCount {
            get {
                return this.AllInOneNumbersCountField;
            }
            set {
                if ((this.AllInOneNumbersCountField.Equals(value) != true)) {
                    this.AllInOneNumbersCountField = value;
                    this.RaisePropertyChanged("AllInOneNumbersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanDownload {
            get {
                return this.CanDownloadField;
            }
            set {
                if ((this.CanDownloadField.Equals(value) != true)) {
                    this.CanDownloadField = value;
                    this.RaisePropertyChanged("CanDownload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientReference {
            get {
                return this.ClientReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientReferenceField, value) != true)) {
                    this.ClientReferenceField = value;
                    this.RaisePropertyChanged("ClientReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasRefunded {
            get {
                return this.HasRefundedField;
            }
            set {
                if ((this.HasRefundedField.Equals(value) != true)) {
                    this.HasRefundedField = value;
                    this.RaisePropertyChanged("HasRefunded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvalidNumbersCount {
            get {
                return this.InvalidNumbersCountField;
            }
            set {
                if ((this.InvalidNumbersCountField.Equals(value) != true)) {
                    this.InvalidNumbersCountField = value;
                    this.RaisePropertyChanged("InvalidNumbersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvalidNumbersFile {
            get {
                return this.InvalidNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.InvalidNumbersFileField, value) != true)) {
                    this.InvalidNumbersFileField = value;
                    this.RaisePropertyChanged("InvalidNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumbersWashed {
            get {
                return this.NumbersWashedField;
            }
            set {
                if ((this.NumbersWashedField.Equals(value) != true)) {
                    this.NumbersWashedField = value;
                    this.RaisePropertyChanged("NumbersWashed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFile {
            get {
                return this.OriginalFileField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalFileField, value) != true)) {
                    this.OriginalFileField = value;
                    this.RaisePropertyChanged("OriginalFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegisteredNumbersCount {
            get {
                return this.RegisteredNumbersCountField;
            }
            set {
                if ((this.RegisteredNumbersCountField.Equals(value) != true)) {
                    this.RegisteredNumbersCountField = value;
                    this.RaisePropertyChanged("RegisteredNumbersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisteredNumbersFile {
            get {
                return this.RegisteredNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredNumbersFileField, value) != true)) {
                    this.RegisteredNumbersFileField = value;
                    this.RaisePropertyChanged("RegisteredNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnregisteredNumbersCount {
            get {
                return this.UnregisteredNumbersCountField;
            }
            set {
                if ((this.UnregisteredNumbersCountField.Equals(value) != true)) {
                    this.UnregisteredNumbersCountField = value;
                    this.RaisePropertyChanged("UnregisteredNumbersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnregisteredNumbersFile {
            get {
                return this.UnregisteredNumbersFileField;
            }
            set {
                if ((object.ReferenceEquals(this.UnregisteredNumbersFileField, value) != true)) {
                    this.UnregisteredNumbersFileField = value;
                    this.RaisePropertyChanged("UnregisteredNumbersFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashingChannelWashingChannelEnum WashingChannel {
            get {
                return this.WashingChannelField;
            }
            set {
                if ((this.WashingChannelField.Equals(value) != true)) {
                    this.WashingChannelField = value;
                    this.RaisePropertyChanged("WashingChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WashingRequestId {
            get {
                return this.WashingRequestIdField;
            }
            set {
                if ((this.WashingRequestIdField.Equals(value) != true)) {
                    this.WashingRequestIdField = value;
                    this.RaisePropertyChanged("WashingRequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dncrapp/", ConfigurationName="DNCRWashingService.IOnlineWashingService")]
    public interface IOnlineWashingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/QuickWash", ReplyAction="http://dncrapp/IOnlineWashingService/QuickWashResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/QuickWashDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashResult QuickWash(SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashRequestArgs quickWashArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/QuickWash", ReplyAction="http://dncrapp/IOnlineWashingService/QuickWashResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashResult> QuickWashAsync(SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashRequestArgs quickWashArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/WashByFileUpload", ReplyAction="http://dncrapp/IOnlineWashingService/WashByFileUploadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/WashByFileUploadDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.WashFileResult WashByFileUpload(SD.ACMA.BusinessLogic.DNCRWashingService.WashFileRequestArgs washFileArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/WashByFileUpload", ReplyAction="http://dncrapp/IOnlineWashingService/WashByFileUploadResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.WashFileResult> WashByFileUploadAsync(SD.ACMA.BusinessLogic.DNCRWashingService.WashFileRequestArgs washFileArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/PreWash", ReplyAction="http://dncrapp/IOnlineWashingService/PreWashResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/PreWashDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.PreWashByFileResult PreWash(SD.ACMA.BusinessLogic.DNCRWashingService.PreWashFileOnlineArgs filePreWashArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/PreWash", ReplyAction="http://dncrapp/IOnlineWashingService/PreWashResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.PreWashByFileResult> PreWashAsync(SD.ACMA.BusinessLogic.DNCRWashingService.PreWashFileOnlineArgs filePreWashArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/DownloadErrorLog", ReplyAction="http://dncrapp/IOnlineWashingService/DownloadErrorLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/DownloadErrorLogDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogResult DownloadErrorLog(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogRequestArgs downloadErrorLogArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/DownloadErrorLog", ReplyAction="http://dncrapp/IOnlineWashingService/DownloadErrorLogResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogResult> DownloadErrorLogAsync(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogRequestArgs downloadErrorLogArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/DownloadWashFile", ReplyAction="http://dncrapp/IOnlineWashingService/DownloadWashFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/DownloadWashFileDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileResult DownloadWashFile(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileRequestArgs downloadWashFileArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/DownloadWashFile", ReplyAction="http://dncrapp/IOnlineWashingService/DownloadWashFileResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileResult> DownloadWashFileAsync(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileRequestArgs downloadWashFileArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/WashHistory", ReplyAction="http://dncrapp/IOnlineWashingService/WashHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SD.ACMA.BusinessLogic.DNCRWashingService.DncrServiceFault), Action="http://dncrapp/IOnlineWashingService/WashHistoryDncrServiceFaultFault", Name="DncrServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Salmat.Dncr.Business.Entities.Core")]
        SD.ACMA.BusinessLogic.DNCRWashingService.WashHistoryRequestResult WashHistory(SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchRequestArgs washingSearchArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dncrapp/IOnlineWashingService/WashHistory", ReplyAction="http://dncrapp/IOnlineWashingService/WashHistoryResponse")]
        System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.WashHistoryRequestResult> WashHistoryAsync(SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchRequestArgs washingSearchArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineWashingServiceChannel : SD.ACMA.BusinessLogic.DNCRWashingService.IOnlineWashingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineWashingServiceClient : System.ServiceModel.ClientBase<SD.ACMA.BusinessLogic.DNCRWashingService.IOnlineWashingService>, SD.ACMA.BusinessLogic.DNCRWashingService.IOnlineWashingService {
        
        public OnlineWashingServiceClient() {
        }
        
        public OnlineWashingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineWashingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineWashingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineWashingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashResult QuickWash(SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashRequestArgs quickWashArgs) {
            return base.Channel.QuickWash(quickWashArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashResult> QuickWashAsync(SD.ACMA.BusinessLogic.DNCRWashingService.QuickWashRequestArgs quickWashArgs) {
            return base.Channel.QuickWashAsync(quickWashArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashFileResult WashByFileUpload(SD.ACMA.BusinessLogic.DNCRWashingService.WashFileRequestArgs washFileArgs) {
            return base.Channel.WashByFileUpload(washFileArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.WashFileResult> WashByFileUploadAsync(SD.ACMA.BusinessLogic.DNCRWashingService.WashFileRequestArgs washFileArgs) {
            return base.Channel.WashByFileUploadAsync(washFileArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.PreWashByFileResult PreWash(SD.ACMA.BusinessLogic.DNCRWashingService.PreWashFileOnlineArgs filePreWashArgs) {
            return base.Channel.PreWash(filePreWashArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.PreWashByFileResult> PreWashAsync(SD.ACMA.BusinessLogic.DNCRWashingService.PreWashFileOnlineArgs filePreWashArgs) {
            return base.Channel.PreWashAsync(filePreWashArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogResult DownloadErrorLog(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogRequestArgs downloadErrorLogArgs) {
            return base.Channel.DownloadErrorLog(downloadErrorLogArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogResult> DownloadErrorLogAsync(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadErrorLogRequestArgs downloadErrorLogArgs) {
            return base.Channel.DownloadErrorLogAsync(downloadErrorLogArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileResult DownloadWashFile(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileRequestArgs downloadWashFileArgs) {
            return base.Channel.DownloadWashFile(downloadWashFileArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileResult> DownloadWashFileAsync(SD.ACMA.BusinessLogic.DNCRWashingService.DownloadWashFileRequestArgs downloadWashFileArgs) {
            return base.Channel.DownloadWashFileAsync(downloadWashFileArgs);
        }
        
        public SD.ACMA.BusinessLogic.DNCRWashingService.WashHistoryRequestResult WashHistory(SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchRequestArgs washingSearchArgs) {
            return base.Channel.WashHistory(washingSearchArgs);
        }
        
        public System.Threading.Tasks.Task<SD.ACMA.BusinessLogic.DNCRWashingService.WashHistoryRequestResult> WashHistoryAsync(SD.ACMA.BusinessLogic.DNCRWashingService.WashingSearchRequestArgs washingSearchArgs) {
            return base.Channel.WashHistoryAsync(washingSearchArgs);
        }
    }
}
