IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FinancialReport' AND COLUMN_NAME = 'MarkedFinalBy')
BEGIN
	ALTER TABLE FinancialReport
		DROP COLUMN MarkedFinalBy
END
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FinancialReport' AND COLUMN_NAME = 'Status')
BEGIN
	ALTER TABLE FinancialReport
		DROP COLUMN Status
END
GO